version: '3.9'

networks:
  traefik:
    external: true

services:
  app:
    image: repo@image
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.services.dev_front_project@name.loadbalancer.server.port=3000'
      - 'traefik.http.services.dev_front_project@name.loadbalancer.passHostHeader=true'
      - 'traefik.http.routers.dev_front_project@name.middlewares=dev_front_project@name_middlewares@file'
      - 'traefik.http.routers.dev_front_project@name.rule=Host(`example.com`)'
      - 'traefik.http.routers.dev_front_project@name.tls.certresolver=lehttp'
      - 'traefik.http.routers.dev_front_project@name.entrypoints=web,websecure'
    networks:
      - traefik